// packages/nc-gui/src/components/blocks/ImageBlock.vue
<template>
  <div class="image-block">
    <img
      v-if="content.url && !editing"
      :src="content.url"
      :alt="content.alt || ''"
      :style="{ width: content.width || '100%' }"
      class="block-image"
    />
    <div v-else-if="editing" class="image-editor">
      <a-input
        v-model:value="localUrl"
        :placeholder="$t('labels.imageUrl')"
        @change="handleContentChange"
      />
      <a-input
        v-model:value="localAlt"
        :placeholder="$t('labels.altText')"
        class="mt-2"
        @change="handleContentChange"
      />
    </div>
    <div v-else class="placeholder">
      {{ $t('labels.noImage') }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'

interface Props {
  id: string
  content: {
    title?: string
    url?: string
    alt?: string
    width?: string
  }
  editing?: boolean
  onUpdate?: (id: string, content: any) => void
}

const props = defineProps<Props>()

const localUrl = ref(props.content?.url || '')
const localAlt = ref(props.content?.alt || '')

watch(
  () => props.content,
  (newContent) => {
    localUrl.value = newContent?.url || ''
    localAlt.value = newContent?.alt || ''
  },
  { deep: true }
)

const handleContentChange = () => {
  props.onUpdate?.(props.id, {
    url: localUrl.value,
    alt: localAlt.value,
  })
}
</script>

<style scoped>
.image-block {
  @apply w-full h-full flex items-center justify-center;
}

.block-image {
  @apply max-w-full max-h-full object-contain;
}

.image-editor {
  @apply w-full p-4;
}

.placeholder {
  @apply text-gray-400 dark:text-gray-500 text-center p-4;
}
</style>

// components/dashboard/blocks/ImageBlock.tsx
"use client";

import { Image as ImageIcon } from "lucide-react";
import BlockHeader from "./BlockHeader";
import { getDefaultContent } from "@/lib/utils/dashboardBlockContent";

interface ImageBlockProps {
  id: string;
  content: any;
  onUpdate?: (id: string, content: any) => void;
  onDelete?: (id: string) => void;
  onOpenSettings?: () => void;
  isDragging?: boolean;
  editing?: boolean;
}

export default function ImageBlock({
  id,
  content,
  onUpdate,
  onDelete,
  onOpenSettings,
  isDragging = false,
  editing = false,
}: ImageBlockProps) {
  // Normalize content with defaults for backwards compatibility
  const defaults = getDefaultContent("image");
  const normalizedContent = { ...defaults, ...content };
  
  const imageUrl = normalizedContent.url || "";
  const caption = normalizedContent.caption || "";
  const style = normalizedContent.style || "contain";
  
  const title = normalizedContent.title || "Image Block";
  
  const imageStyle = style === "cover" 
    ? "object-cover w-full h-full" 
    : style === "full-width"
    ? "w-full"
    : "object-contain w-full";

  return (
    <>
      <BlockHeader
        title={title}
        editing={editing}
        onOpenSettings={onOpenSettings || (() => {})}
        onDelete={onDelete ? () => onDelete(id) : undefined}
        isDragging={isDragging}
      />
      <div className="flex-1 overflow-y-auto p-4 flex items-center justify-center">
        {!imageUrl ? (
          <div className="text-center py-8 text-gray-500 text-sm">
            <ImageIcon className="w-12 h-12 mx-auto mb-2 text-gray-400" />
            <p>No image</p>
            <p className="text-xs mt-1">Configure in settings</p>
          </div>
        ) : (
          <div className="w-full">
            <img
              src={imageUrl}
              alt={caption || "Dashboard image"}
              className={`${imageStyle} rounded-lg`}
            />
            {caption && (
              <p className="mt-2 text-sm text-gray-600 dark:text-gray-400 text-center">
                {caption}
              </p>
            )}
          </div>
        )}
      </div>
    </>
  );
}
