// packages/nc-gui/src/components/blocks/ImageBlock.vue
<template>
  <div class="image-block">
    <img
      v-if="content.url && !editing"
      :src="content.url"
      :alt="content.alt || ''"
      :style="{ width: content.width || '100%' }"
      class="block-image"
    />
    <div v-else-if="editing" class="image-editor">
      <a-input
        v-model:value="localUrl"
        :placeholder="$t('labels.imageUrl')"
        @change="handleContentChange"
      />
      <a-input
        v-model:value="localAlt"
        :placeholder="$t('labels.altText')"
        class="mt-2"
        @change="handleContentChange"
      />
    </div>
    <div v-else class="placeholder">
      {{ $t('labels.noImage') }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'

interface Props {
  id: string
  content: {
    title?: string
    url?: string
    alt?: string
    width?: string
  }
  editing?: boolean
  onUpdate?: (id: string, content: any) => void
}

const props = defineProps<Props>()

const localUrl = ref(props.content?.url || '')
const localAlt = ref(props.content?.alt || '')

watch(
  () => props.content,
  (newContent) => {
    localUrl.value = newContent?.url || ''
    localAlt.value = newContent?.alt || ''
  },
  { deep: true }
)

const handleContentChange = () => {
  props.onUpdate?.(props.id, {
    url: localUrl.value,
    alt: localAlt.value,
  })
}
</script>

<style scoped>
.image-block {
  @apply w-full h-full flex items-center justify-center;
}

.block-image {
  @apply max-w-full max-h-full object-contain;
}

.image-editor {
  @apply w-full p-4;
}

.placeholder {
  @apply text-gray-400 dark:text-gray-500 text-center p-4;
}
</style>

// baserow-app/components/interface/blocks/ImageBlock.tsx
"use client"

import { useState } from "react"
import type { PageBlock } from "@/lib/interface/types"
import { Image as ImageIcon } from "lucide-react"

interface ImageBlockProps {
  block: PageBlock
  isEditing?: boolean
  onUpdate?: (url: string, alt: string) => void
}

export default function ImageBlock({ block, isEditing = false, onUpdate }: ImageBlockProps) {
  const { config } = block
  const imageUrl = config?.image_url || ""
  const imageAlt = config?.image_alt || ""
  const [url, setUrl] = useState(imageUrl)
  const [alt, setAlt] = useState(imageAlt)

  function handleBlur() {
    if (onUpdate && (url !== imageUrl || alt !== imageAlt)) {
      onUpdate(url, alt)
    }
  }

  if (isEditing) {
    return (
      <div className="h-full p-4 space-y-2">
        <input
          type="url"
          value={url}
          onChange={(e) => setUrl(e.target.value)}
          onBlur={handleBlur}
          className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm"
          placeholder="Image URL"
        />
        <input
          type="text"
          value={alt}
          onChange={(e) => setAlt(e.target.value)}
          onBlur={handleBlur}
          className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm"
          placeholder="Alt text"
        />
        {url && (
          <div className="mt-2">
            <img
              src={url}
              alt={alt}
              className="max-w-full h-auto rounded-md"
              onError={(e) => {
                e.currentTarget.style.display = "none"
              }}
            />
          </div>
        )}
      </div>
    )
  }

  if (!imageUrl) {
    return (
      <div className="h-full flex items-center justify-center text-gray-400">
        <ImageIcon className="h-8 w-8" />
      </div>
    )
  }

  return (
    <div className="h-full p-4 flex items-center justify-center">
      <img
        src={imageUrl}
        alt={imageAlt}
        className="max-w-full max-h-full object-contain rounded-md"
        onError={(e) => {
          e.currentTarget.style.display = "none"
          const parent = e.currentTarget.parentElement
          if (parent) {
            parent.innerHTML = '<div class="text-gray-400 text-sm">Failed to load image</div>'
          }
        }}
      />
    </div>
  )
}
